<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>10</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Silk.NET.Vulkan\Silk.NET.Vulkan.csproj"/>
  </ItemGroup>

  <Import Project="..\..\..\build\props\bindings.props"/>
</Project>
