name: Publish NuGet packages

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  nuget:
    name: Publish NuGet packages
    runs-on: ubuntu-24.04

    steps:

      - name: Login to NuGet
        uses: NuGet/login@v1
        id: nuget
        with:
          user: ${{ vars.NUGET_PUBLISH_USERNAME }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.100"

      - name: Cache .git folder
        uses: actions/cache@v6
        with:
          path: .git
          key: git-silk3-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/.gitmodules') }}

      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          lfs: false
          fetch-depth: 0
          filter: tree:0

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack
        run: dotnet pack --configuration Release --no-build

      - name: Save packages as artifact
        uses: actions/upload-artifact@v5
        with:
          name: Packages
          path: ./outputs/nuget/Release/

      - name: Publish
        run: dotnet nuget push ./outputs/nuget/Release/**/*.nupkg --skip-duplicate --api-key ${{ steps.nuget.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
