name: Update parent repo

on:
  workflow_dispatch:
  push:
    branches:
      - silk2
      - silk3

permissions:
  contents: read

jobs:
  sync-silk2:
    name: Update parent repo (silk2)
    if: github.ref_name == 'silk2'
    uses: Exanite-GameDev/Exanite.GameDev/.github/workflows/update-parent.reusable.yml@main
    with:
      target_repo: Exanite-GameDev/Exanite.GameDev
      target_submodule: projects/Silk2.NET
      target_branch: main
    secrets:
      _GITHUB_TOKEN_SUBMODULE_SYNC: ${{ secrets._GITHUB_TOKEN_SUBMODULE_SYNC }}

  sync-silk3:
    name: Update parent repo (silk3)
    if: github.ref_name == 'silk3'
    uses: Exanite-GameDev/Exanite.GameDev/.github/workflows/update-parent.reusable.yml@main
    with:
      target_repo: Exanite-GameDev/Exanite.GameDev
      target_submodule: projects/Silk3.NET
      target_branch: main
    secrets:
      _GITHUB_TOKEN_SUBMODULE_SYNC: ${{ secrets._GITHUB_TOKEN_SUBMODULE_SYNC }}
